# Generated by Django 2.1 on 2019-01-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='配件名')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('city', models.CharField(choices=[('YZ', '扬州'), ('BJ', '北京'), ('CQ', '重庆')], max_length=8, verbose_name='城市')),
                ('note', models.CharField(max_length=128, verbose_name='备注')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('who_does', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name_plural': '配件库',
            },
        ),
    ]
