# Generated by Django 2.1 on 2019-01-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Item', verbose_name='配件'),
        ),
    ]
