# Generated by Django 2.1 on 2019-01-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190121_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-operated_time',), 'verbose_name_plural': '操作记录'},
        ),
    ]
