# Generated by Django 2.1 on 2019-01-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190124_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '配件', 'verbose_name_plural': '配件'},
        ),
    ]
