# Generated by Django 2.1 on 2019-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190125_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField(verbose_name='单号')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='发货日期')),
                ('server_type', models.CharField(choices=[('wifi', 'wifi服务器'), ('video', '视频服务器')], max_length=20, verbose_name='型号')),
                ('server_num', models.IntegerField(verbose_name='数量')),
                ('note_text', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '发货记录',
                'verbose_name_plural': '发货记录',
                'ordering': ('-post_date',),
            },
        ),
    ]
