# Generated by Django 2.1 on 2019-02-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_postmanage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-operated_time',), 'verbose_name': '操作记录', 'verbose_name_plural': '操作记录'},
        ),
    ]
