# Generated by Django 2.1 on 2019-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190221_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='post_date',
            field=models.DateTimeField(verbose_name='发货日期'),
        ),
    ]
