# Generated by Django 2.1 on 2019-03-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_operation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=8, verbose_name='设备ID')),
                ('sim_card', models.CharField(max_length=13, verbose_name='sim卡号')),
            ],
            options={
                'verbose_name': 'sim卡',
                'verbose_name_plural': 'sim卡',
            },
        ),
    ]
