# Generated by Django 2.1 on 2019-03-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['qty'], 'verbose_name': '配件', 'verbose_name_plural': '配件'},
        ),
        migrations.AddField(
            model_name='postmanage',
            name='post_type',
            field=models.CharField(choices=[('send', '发货'), ('receive', '回收')], default='send', max_length=8, verbose_name='收寄类型'),
        ),
    ]
