# Generated by Django 2.1 on 2019-03-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190322_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='post_num',
            field=models.CharField(max_length=12, verbose_name='单号'),
        ),
    ]
