# Generated by Django 2.1 on 2019-01-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.CharField(choices=[('plus', '增加'), ('minus', '减少')], max_length=8, verbose_name='操作')),
                ('num', models.IntegerField(verbose_name='数目')),
                ('operated_time', models.DateTimeField(auto_now_add=True, verbose_name='操作日期')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Item')),
            ],
            options={
                'verbose_name_plural': '操作记录',
            },
        ),
    ]
